### ISSUE TITLE
Back camera error handling

### ISSUE THREAD

**Issue by maresnavilo** [Temasys/skylink-android-sample#2]
Hi everyone,
In the videoChat sample there is no error handling in case there is an error getting the front camera. If I have only back camera, the app crashes. If I try to switch the camera in order to get the back camera, I get this error:
E/sg.com.temasys.skylink.sdk.rtc.cb﹕ Failed to switch camera. Number of cameras: 0.

Thank you,

**Comment by goddino** [comment]
Hi @maresnavilo this is scheduled to be fixed in the next update.
Thanks for trying us out!
