### ISSUE TITLE
Need to display GLSurfaceView as circular 

### ISSUE THREAD

**Issue by khazova** [Temasys/skylink-android-sample#3]
Hello,

We need to make circular GLSurfaceView for the self preview, temasys sdk provide GLSurfaceView from its override method "**onRemotePeerMediaReceive**"  of  MediaListener interface and its already rendered. so how can i make it circular by overriding it.

Thank you.

**Comment by bhaumik2712** [comment]
is there any solution to make GLSurfaceView as circular?

**Comment by goddino** [comment]
Making the provided SurfaceViewRenderer circular is not part of the SDK support.
However, you may try on your own to modify the SurfaceViewRenderer provided to make it circular.
One possible reference is as follows:
http://stackoverflow.com/questions/21001721/android-creating-a-circular-mask-on-video

Note that a SurfaceViewRenderer is also a SurfaceView.

**Comment by bhaumik2712** [comment]
Thanks for the info !
