### ISSUE TITLE
Android to iOS call not working

### ISSUE THREAD

**Issue by SanjayAndroidDev** [Temasys/skylink-android-sample#4]
Hi, I am developing a demo application using this sdk. But I can't able to call android/iOS device together.

**Comment by lyx501135** [comment]
Hi Sanjay,

Please make sure you have the same app key for both Android and iOS, and the two devices are in the same room

**Comment by exera-development** [comment]
Hello,
I'm facing with the same problem, I'm using the same app key and the same room, but only a black screen appears. The interesting thing is that with android emulator works.

**Comment by lyx501135** [comment]
Please use this branch for iOS https://github.com/Temasys/SKYLINK-iOS/tree/VOLTE_IPv6

**Comment by lyx501135** [comment]
This will be the next release

**Comment by exera-development** [comment]
I added the library like this:
pod 'SKYLINK', :git => 'https://github.com/Temasys/SKYLINK-iOS.git', :branch => 'VOLTE_IPv6'
but, still not works. Only difference is that now not even the black screen appears, nothing happens when both ios and android is connected to the same 1:1 video chat room

**Comment by lyx501135** [comment]
This build works well on both Wifi and 4G for all customers. Please delete the app on your device, clear build cache and reinstall it, thanks 

Yuxi
