### ISSUE TITLE
Video view padding in new android release 0.11.0

### ISSUE THREAD

**Issue by gmrm** [Temasys/skylink-android-sample#5]
Hi ...
I am Gh Mustafa from OnlineCare LLC. Just found and tested your new android release .
In MultiPartyVideoCallFragment when a video call is established there is a horizontal padding/ space between video views which really looks not good. In your previous release it was fine. All video vies were fixed i.e 1/4 th part of screen for each video view. But in this release there is space above in middle and in bottom of the screen. 
Please let us know how can we remove this space

**Comment by gmrm** [comment]
Hi ... I have found the solution.

I fount the method setLayoutParams(SurfaceViewRenderer videoView) in that fragment.

It was specified wrap_content. So changing it to match_parent solved my problem.

Bundles of thanks for you time and support :-)

Thankyou skylink team .

All the best

**Comment by lyx501135** [comment]
Thanks man 👍🏻
