### ISSUE TITLE
Unable to connect to room!

### ISSUE THREAD

**Issue by exera-development** [Temasys/skylink-android-sample#6]
Hello,
when I'm trying to connect to a video room but I'm getting the following error:
10-29 17:28:47.768 1000-1000/sg.com.temasys.skylink.sampleapp_0_10_0 D/sg.com.temasys.skylink.sdk.sampleapp.Utils: Skylink failed to connect!
    Reason : [ERROR:36] Unable to connect to room!
    Details: Room params from App Server has error!
    Server Error: 404
    Server Info: App ID is invalid
    Aborting connect to room...

**Comment by iyharini** [comment]
Hi, you may wish to refer to our Troubleshooting Guide on this particular error message here: http://support.temasys.com.sg/support/solutions/articles/12000050877-error-404-app-id-is-invalid
I hope this helps.
