### ISSUE TITLE
Could not resolve skylink.sdk:skylink_sdk:2.0.0-RELEASE

### ISSUE THREAD

**Issue by niravtopsy** [Temasys/skylink-android-sample#7]
Getting issue after clone,

Unable to resolve dependency for ':sampleapp@debug/compileClasspath': Could not resolve sg.com.temasys.skylink.sdk:skylink_sdk:2.0.0-RELEASE.

@lyx501135 @ChickChik @goddino

**Comment by muoipham** [comment]
Thank you for letting us know about the issue. We have fixed it recently. Please try again!

**Comment by niravtopsy** [comment]
@muoipham please help me to find out which is latest branch in that you solve it.

**Comment by muoipham** [comment]
hi @niravtopsy , we solved the issue on all branches, pls use the master branch.
Thanks
